### ISSUE TITLE
How do I enable the multiple scale option?

### ISSUE THREAD

**Issue by LightingMc** [vitoralbiero/img2pose#11]
Hey,
  I am trying to reproduce some results that you showed on the BIWI and ALFW-2000-3D datasets. The code that you have given in the evaluation notebooks is carrying out the non-multi scale option, How do I enable the multiscale option?

![image](https://user-images.githubusercontent.com/42900802/108856568-32b3ab80-75b8-11eb-975b-5465a4eabc2a.png)

**Comment by vitoralbiero** [comment]
On each evaluation notebook, when you run the model on the images, there's a for loop for the image size, you just need to add the sizes that you want there.
For AFLW2000-3D, change the line **for size in (400,):** to **for size in (350, 400, 450, 500, 550,):**
For BIWI, change the line **for size in (600,):** to **for size in (480, 600, 800, 1000, 1200,):**

Hope this helps.
