### ISSUE TITLE
Can this model be applied to face recognition

### ISSUE THREAD

**Issue by love112358** [vitoralbiero/img2pose#12]
Hello, I want to ask a question, can this model be applied to face recognition? Can you give me some ideas

**Comment by vitoralbiero** [comment]
Hello, you can use our code to detect and align faces to use with any face recognition model.
Our method was not designed to perform face recognition, so if you want to do that using our code, you will need to change the training pipeline to have an additional face recognition classifier, face recognition loss, data loader with identity classes, etc. Basically, all the components needed to perform face recognition.

Hope this helps.
