### ISSUE TITLE
lack of three pretrainedmodels

### ISSUE THREAD

**Issue by hsl20130659** [vitoralbiero/img2pose#16]
FileNotFoundError: [Errno 2] No such file or directory: '../../models/WIDER_train_pose_mean_v1.npy'
FileNotFoundError: [Errno 2] No such file or directory: '../../models/WIDER_train_pose_stddev_v1.npy'
FileNotFoundError: [Errno 2] No such file or directory: '../../models/img2pose_v1.pth'

**Comment by hsl20130659** [comment]
When I run the test_own_images.ipynb , it can not find the pretrained models , is it convenient to release these 3 models

**Comment by tkianai** [comment]
Hi, pretrained models are listed here, https://github.com/vitoralbiero/img2pose/wiki/Model-Zoo

**Comment by vitoralbiero** [comment]
As @tkianai said, models are available at https://github.com/vitoralbiero/img2pose/wiki/Model-Zoo

Thanks.
