### ISSUE TITLE
Units of translation vector

### ISSUE THREAD

**Issue by alyonamoryakova** [vitoralbiero/img2pose#19]
Hello. Help me figure out in what units are the translation vector returned? I am trying to determine how far a person is from the camera using img2pose model. It seems that X and Y are not measured in the same units as Z. And I can't figure out what these units are. Help me please.

**Comment by vitoralbiero** [comment]
Hello,

The units in the translation vector (tvec) are arbitrary units of the 3D face model used as a reference to annotate the images, they do not represent pixels or other human-understandable units.

The tvec is the same as the output of SolvePnP from OpenCV, and you can read more about it here https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d

Hope this helps.
