### ISSUE TITLE
Whether the prediction of 6DOF can be completed through one-stage detector?

### ISSUE THREAD

**Issue by mifan0208** [vitoralbiero/img2pose#24]
Direct face detection through 6DOF is a great activity. Can this task be completed directly through the one-stage method?
Thanks~

**Comment by vitoralbiero** [comment]
Hello,
Thanks for your interest in our work.

We believe that with the appropriate modifications, the contributions of our paper could be indeed applied to a one-stage framework, replacing the standard face detection.
