### ISSUE TITLE
Why does mode size differ between trained model and your released model?

### ISSUE THREAD

**Issue by KindleHe** [vitoralbiero/img2pose#25]
when running the training scripts as the readme, the generated model size is 324M, 
while your released model in [model zoo](https://github.com/vitoralbiero/img2pose/wiki/Model-Zoo) only ~150M
```
CUDA_VISIBLE_DEVICES=0 python3 train.py \
--pose_mean ./datasets/lmdb/WIDER_train_annotations_pose_mean.npy \
--pose_stddev ./datasets/lmdb/WIDER_train_annotations_pose_stddev.npy \
--workspace ./workspace/ \
--train_source ./datasets/lmdb/WIDER_train_annotations.lmdb \
--val_source ./datasets/lmdb/WIDER_val_annotations.lmdb \
--prefix trial_2 \
--batch_size 2 \
--lr_plateau \
--early_stop \
--random_flip \
--random_crop \
--max_size 1400
```

**Comment by vitoralbiero** [comment]
During training, the model optimizer is saved along with the model (check [here](https://github.com/vitoralbiero/img2pose/blob/main/model_loader.py#L15)), which adds another ~170MB to the file.
This is useful in case your training fails and you want to resume at the same point.

The final released model does not contain the optimizer, only the model.

**Comment by KindleHe** [comment]
Thans very much for your reply!
