### ISSUE TITLE
Not able to evaluate images using the file test_own_images.ipynb

### ISSUE THREAD

**Issue by 97jay** [vitoralbiero/img2pose#26]
First of all, thank you for your work. I am trying to run "test_own_images.ipynb" evaluation but I am getting the error "the size of tensor a must match the size of tensor b at non-singleton dimension 0" at line  "res = img2pose_model.predict([transform(img)])[0]". I am trying to use images from CASIA webface and MultiPIE dataset. Please let me know I should I solve this.

**Comment by vitoralbiero** [comment]
Hello,

Thanks for your interest in our work.

If you run plt.imshow(img) does it display correctly the images?
Also, could you post the full error?

**Comment by 97jay** [comment]
![Capture](https://user-images.githubusercontent.com/71685328/112071334-e96a6380-8b45-11eb-9313-9f8ba78a4ce6.JPG)

I have attached the screenshot of error here. I tried saving the input image and it is correctly saving. I am running 'test_own_images.ipynb' as a '.py' file(in case you are wondering how I am testing a '.py' file). The size of these images are 250 x 250 x 3. Please let me know what it is. Thank you

**Comment by vitoralbiero** [comment]
I think the problem is that the models is trying to use 2 GPUs, but dataparell is not currently supported.
Try running the code as:
```
CUDA_VISIBLE_DEVICES=0 python test_images.py
```

**Comment by 97jay** [comment]
Thank you so much. That error is gone now. I am facing other attribute errors which I think I will be able to solve. Thank you once again for your prompt response.

**Comment by vitoralbiero** [comment]
No problem, glad the issue was solved.
