### ISSUE TITLE
What is the difference between the constrained and unconstrained head pose model?

### ISSUE THREAD

**Issue by LightingMc** [vitoralbiero/img2pose#29]

**Comment by vitoralbiero** [comment]
The unconstrained model was trained on WIDER FACE dataset as the v1 of our paper describes.
Starting from the unconstrained model, the constrained version was fine-tuned on 300W-LP dataset, which only includes head poses in the range (-90, 90).
We are going to release a new version of the paper that talks about the unconstrained model.

Hope this clarifies your question.

**Comment by KindleHe** [comment]
> The unconstrained model was trained on WIDER FACE dataset as the v1 of our paper describes.
> Starting from the unconstrained model, the constrained version was fine-tuned on 300W-LP dataset, which only includes head poses in the range (-90, 90).
> We are going to release a new version of the paper that talks about the unconstrained model.
> 
> Hope this clarifies your question.

How to fine-tune the unconstrained model on 300W-LP dataset, which only includes head poses in the range (-90, 90) ?
Could you please share the training scripts to get the img2pose_v1_ft_300w_lp.pth model released ?
