### ISSUE TITLE
how to optimize and speed up the alignment code?

### ISSUE THREAD

**Issue by Jar7** [vitoralbiero/img2pose#34]
Hello, thank your for your work.
I read the alignment code and found there is a pytorch version alignment function. Can it be used for inference? Do you think it is possible to align faces by batch or any other ways to speed up the alignment process? like run in gpu?
Thank you!

**Comment by vitoralbiero** [comment]
Hello @Jar7,
Thanks for your interest in our work!

Right now on the ```run_alignment.py``` script, inference is running [one image at a time](https://github.com/vitoralbiero/img2pose/blob/main/run_face_alignment.py#L70), but you could easily modify it to run on a batch of images and then perform alignment on each one.
I haven't measured the time necessary for the [alignment part](https://github.com/vitoralbiero/img2pose/blob/main/run_face_alignment.py#L106) of the script, but I believe it to be negligible compared to the inference time.
If you decide to make improvements, PRs are welcome!

Hope this helps.
