### ISSUE TITLE
how  Sim3DR render color?

### ISSUE THREAD

**Issue by dyther** [vitoralbiero/img2pose#35]
I want to use Sim3DR to render a face with color but I get wrong img
I use this fuction
Sim3DR_Cython.rasterize(bg, vertices, triangles, colors, buffer, triangles.shape[0], height, width, channel,
                            reverse=reverse)

and input colors (N ,3) 
![image](https://user-images.githubusercontent.com/24862135/117574886-e46f6c80-b111-11eb-8d1a-20b0fcb7e8dd.png)

**Comment by vitoralbiero** [comment]
Hello,

Sim3DR was forked from https://github.com/cleardusk/3DDFA_V2/tree/master/Sim3DR, so I encourage you to post your question there, as we used it here as is, and we haven't tried render with colors.
Hope this helps.
