### ISSUE TITLE
focal length and image resolution

### ISSUE THREAD

**Issue by gravitychen** [vitoralbiero/img2pose#39]
Can you explain why you set the focal length equals w+h (for the global camera)? I checked some articles, and their conclusion is also that higher resolution leads to higher focal length, I know it is a way to approximate, but I still cannot fully understand the reason behind this. Thank you very much~

**Comment by vitoralbiero** [comment]
Hello @gravitychen,

The focal length of ``` w + h ``` was an arbitrary choice. You just need to be consistent with the focal length you use to create GT data for training, and the focal length when testing.

Hope this helps.

**Comment by gravitychen** [comment]
Yes, I just curious about why this assumption works because the visualization result make sense so far~

**Comment by vitoralbiero** [comment]
Yeah, we didn't try other focal lengths, but it should work if they are consistent, and the visualization should be the same then.
