### ISSUE TITLE
How do I extract the head position feature

### ISSUE THREAD

**Issue by lqsunshine** [vitoralbiero/img2pose#41]
the last question has been solved. Thank you very much for your answer. If I want to extract the head posture features for downstream tasks, which layer of output in the network should I extract. The output doesn't take into account the position of the face but only the direction of the head. module.roi_heads.class_head.fc7？

**Comment by vitoralbiero** [comment]
Yes, that is the feature that is input to both the 6DoF pose head and class head, so you can use it for downstream tasks.
If you want more specialized pose features, you can grab them from the last but one layer on the FastRCNNDoFPredictor ("box_predictor").
Just know that both these features correspond to the local pose, and a post-processing step (pose conversion algorithm described in the paper) is used to convert the pose prediction to a global pose (w.r.t. to the full image).

Hope this helps.

**Comment by vitoralbiero** [comment]
Actually no, ```module.roi_heads.class_head.fc7``` is the input to the face classification head.

You can extract from ``` module.roi_heads.box_head.fc7 ```, which is the input to the 6DoF head.
If you want more specialized pose features, you can grab them from the last but one layer on the FastRCNNDoFPredictor ("box_predictor").
Just know that both these features correspond to the local pose, and a post-processing step (pose conversion algorithm described in the paper) is used to convert the pose prediction to a global pose (w.r.t. to the full image).

Hope this helps.

**Comment by lqsunshine** [comment]
> Actually no, `module.roi_heads.class_head.fc7` is the input to the face classification head.
> 
> You can extract from `module.roi_heads.box_head.fc7`, which is the input to the 6DoF head.
> If you want more specialized pose features, you can grab them from the last but one layer on the FastRCNNDoFPredictor ("box_predictor").
> Just know that both these features correspond to the local pose, and a post-processing step (pose conversion algorithm described in the paper) is used to convert the pose prediction to a global pose (w.r.t. to the full image).
> 
> Hope this helps.
Thanks so much!
