### ISSUE TITLE
How to determine the final pose for my own image?

### ISSUE THREAD

**Issue by sukun1045** [vitoralbiero/img2pose#42]
Hi, I have a question regarding the final pose I should use for my own image. Since there are multiple `pose_pred` that have high scores while they have similar values. In AFLW evaluation, you determine the best index using max_iou. In `test_own_images`, it seems like you use all high score predicted poses to render (That is what I understand the `overlap` variable in `renderer.render`). In my case, I just want to obtain the pose only. Would it be the average of all high score predictions or simply using the highest score result? Or any other solution? Thank you.

**Comment by vitoralbiero** [comment]
Hello @sukun1045,

I use all the high scores because they correspond to multiple faces. That notebook should work for you even if you have a single face in the image, as the model should only output a single pose per face.

Hope this helps.

**Comment by sukun1045** [comment]
Thanks for your reply!
