### ISSUE TITLE
 test_own_images

### ISSUE THREAD

**Issue by sayoko17** [vitoralbiero/img2pose#43]
when i run the notebook test_own_images, in the last cell . i have a problem.
![image](https://user-images.githubusercontent.com/54976956/128864980-58acff2f-e5cb-4940-b1ce-72f069b09865.png)
how can i do,please help me , thank you!

**Comment by vitoralbiero** [comment]
Hello @sayoko17,

Thanks for your interest in our project.
This error occurs when you have more than one GPU on the machine running the notebook. 
To fix it, you can call the jupyter notebook like ```CUDA_VISIBLE_DEVICES=0 jupyter notebook```, this way it will only see the first GPU. You can also do that in the code, but this way is faster.

This should fix your problem, so I am closing this issue. Feel free to reopen it if the error persists after trying this step.
