### ISSUE TITLE
smooth_l1_loss not part of models.detection

### ISSUE THREAD

**Issue by dk-teknologisk-mlnn** [vitoralbiero/img2pose#48]
Getting error:  
File "C:\Code\Python\img2pose-main\rpn.py", line 467, in compute_loss
    det_utils.smooth_l1_loss(
AttributeError: module 'torchvision.models.detection._utils' has no attribute 'smooth_l1_loss'

**Comment by dk-teknologisk-mlnn** [comment]
replaced with torch.nn.functional.smooth_l1_loss and is can now train, albeit with warnings: 

UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
C:\Anaconda3\envs\pytorch-pose\lib\site-packages\torch\_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)

**Comment by vitoralbiero** [comment]
Hello @sequoiagrove,

Which version of PyTorch are you using? As I don't get this error when using PyTorch 1.7.1
