### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by tkzky** [vitoralbiero/img2pose#50]
Hello. I have some questions:
1. Tz is the front/back distance between the face and the camera, I'd like to know how accurate it is in mm?
2. Can I get the PLY format for the face reconstruction model?

Looking for your reply! Thank you!

**Comment by vitoralbiero** [comment]
Hello @tkzky,

Thank you for your interest in our work!

1. T<sub>z</sub> is an arbitrary value between the 3D face model and the ground-truth points. We don't have the accuracy in mm, only in this arbitrary measurement.
2. We don't have the PLY object saved, but you can use the code [here](https://github.com/vitoralbiero/img2pose/blob/main/utils/renderer.py#L89) so export OBJ files.

Hope this helps.
