### ISSUE TITLE
Redundant output of the `box_predictor` and `class_predictor` of the second phase network

### ISSUE THREAD

**Issue by FunkyKoki** [vitoralbiero/img2pose#51]
Thanks for your contribution at first, I learned a lot from your work!

However, I found that you continue to config the predictor by setting `num_classes=2` as [this line](https://github.com/vitoralbiero/img2pose/blob/10c1a543a0d5e092b965752a48c3741ed4ed7130/img2pose.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L67) shows.

As I think, since the whole network is used for human face only, there is no need to set in this way, which will lead to redundant parameters usage.

Is there any reason to do so? Or this could be refined for further parameters saving?

Thanks for your attention.

**Comment by FunkyKoki** [comment]
By the way, [these code](https://github.com/vitoralbiero/img2pose/blob/10c1a543a0d5e092b965752a48c3741ed4ed7130/losses.py#L51-L56) are redundant as well, since the input params of this rcnn_loss are already positive proposals, labels and so on.

**Comment by vitoralbiero** [comment]
Hello @FunkyKoki,
Thank you for your interest in our work.
Yes, you could simplify the code to use just 1 class, but since we are using the standard Faster R-CNN implementation, the background class is required: `num_classes (int): number of output classes (including background`.

Hope this helps.

**Comment by FunkyKoki** [comment]
All right, thanks for your reply. 😃
