### ISSUE TITLE
Questions about pose pred

### ISSUE THREAD

**Issue by eugeneYz** [vitoralbiero/img2pose#56]
1.What is the output measurement unit :pose_pred: [array([ 0.14125733, -0.02719707, -0.01702601,  0.0928278 ,  0.5363695 ,12.56241608])]  rx, ry,rz in rad and tx ty tz in cm?
2. What is the center of pose ? Is the pix center of box?
Thank you!

**Comment by eugeneYz** [comment]
‘Cause I tried to test the pose_pred on my web cam and found the result of translation in z-axis a huge error.Does it relate to the camera intrinsic? Looking forward to your comment!

**Comment by vitoralbiero** [comment]
The rotation output is in radians, and the translation is an arbitrary value.
If you want to read more about the output, it is the same format as [OpenCV's SolvePnP](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga357634492a94efe8858d0ce1509da869).

The camera intrinsic should be defined in the same way as we do, if you changed that, you will not get an accurate prediction.

Hope this helps.

**Comment by eugeneYz** [comment]
Sorry,I still confused about the head translation an arbitrary value.What if the output be [array([ 0.14125733, -0.02719707, -0.01702601, 0.0928278 , 0.5363695 ,12.56241608]) . What is the unit of lenth?
