### ISSUE TITLE
Alignment issue: Assertion error

### ISSUE THREAD

**Issue by LightingMc** [vitoralbiero/img2pose#6]
First of all, excellent work. I love the work that you have done.

Now coming to the matter at hand: I am getting the assertion error below when I try to run the face alignment thing in **aflw_2000_3d_evaluation.ipynb**. 

![image](https://user-images.githubusercontent.com/42900802/107871373-ddb4be80-6e6e-11eb-8d71-8eb1b19683ab.png)

1. The **total_imgs** variable is reduced to 1.
![image](https://user-images.githubusercontent.com/42900802/107871434-777c6b80-6e6f-11eb-844d-c0e00b63467c.png)
2. Tried with the **visualise** variable both on and off.
3. Called the variable both within and outside the loop.

**Outside**:

![image](https://user-images.githubusercontent.com/42900802/107871532-81529e80-6e70-11eb-97ee-6c928327d67b.png)

**Within**:

![image](https://user-images.githubusercontent.com/42900802/107871545-a34c2100-6e70-11eb-89df-43d156863899.png)

And my lmk.shape is 68,2

**Comment by vitoralbiero** [comment]
Thanks for your interest in our work.
The align_faces method was implemented to use 5 points for alignment.
So, to fix your problem, load and pass the file **pose_references/reference_3d_5_points_trans.npy** when calling **align_faces**.

Hope this helps.
