### ISSUE TITLE
Question for face alignment

### ISSUE THREAD

**Issue by FunkyKoki** [vitoralbiero/img2pose#60]
Thanks again for your work.

I am curious about one another thing. In your paper, you try to convince the readers about the superiority of regressing 6DoF directly from the original image (without landmark regression). However, how to align the corresponding faces according to the 6DoF information?

**Comment by vitoralbiero** [comment]
We use the 6DoF to project points from the 3D model into the image. Then, we use those points for alignment.
See the code in [here](https://github.com/vitoralbiero/img2pose/blob/main/run_face_alignment.py#L106).

**Comment by FunkyKoki** [comment]
Thank you, I did not notice that.
