### ISSUE TITLE
Pose to angle

### ISSUE THREAD

**Issue by mrelmi** [vitoralbiero/img2pose#62]
Thanks for your great work!
How can i convert poses or rotation matrix to angles in gradient ?

**Comment by vitoralbiero** [comment]
Hello @mrelmi,

Thank you for your interest in our work!

Our rotation vectors are expressed in radians. You can convert them to degrees `radians * 180/pi`, and then convert to gradians `degrees * 1.111111`. Or, you can convert directly as `radians * 200/pi`,

Hope this helps.
