### ISSUE TITLE
Question about BIWI evaluation

### ISSUE THREAD

**Issue by HarryXD2018** [vitoralbiero/img2pose#7]
Hello, 

In `evaluation/jupyter_notebooks/biwi_evaluation.ipynb`, the annotations file is opened with `dataset_path = "./BIWI_annotations.txt"`, however, I didn't find that file in the BIWI dataset. I download the dataset from the link you provided at `readme`. 

Would you please tell me where can I find this file? I would be highly appreciated it. 

Cheers, 
Harry.

**Comment by vitoralbiero** [comment]
Hello,
The BIWI_annotations.txt is in the same folder as the notebook you are trying to run: https://github.com/vitoralbiero/img2pose/blob/main/evaluation/jupyter_notebooks/BIWI_annotations.txt

Hope this helps.
Vítor.
