### ISSUE TITLE
A Question about the 6DoF

### ISSUE THREAD

**Issue by wangzixing1998** [vitoralbiero/img2pose#75]
great job! However，In this code, I noticed that the projected box and image was scaled while training and inference, but nothing was done to the pose. I don't understand why.  I would appreciate it if you can help me.

**Comment by vitoralbiero** [comment]
Hello @wangzixing1998,

So the pose doesn't need to be scaled, as what control the scale of it is the image intrinsics matrix, which is defined based on the image size.
Example, if you have an image 100x100, or 200x200, the pose will still be the same, only the intrinsics will need to be changed.
We do that when performing the calibration point loss, check [here](https://github.com/vitoralbiero/img2pose/blob/main/losses.py#L82).

Hope this helps.

**Comment by wangzixing1998** [comment]
I get it. Thank you very much. there still a question about the function "convert_to_aflw", why the return is "np.array([angle[0], -angle[1], -angle[2]])"， the yaw and roll are Negative numbers.
