### ISSUE TITLE
mAP and plot curves

### ISSUE THREAD

**Issue by LightingMc** [vitoralbiero/img2pose#8]
Hey, 
    So I downloaded the eval_tools.zip file. However, I don't really understand what to do with it to get the mAP and plot curves. Like  I unzipped it and it has **a lot** of matlab type of files in it. Could you be kindly a bit more clear as to which files to run?
Regards,
Zaigham

**Comment by vitoralbiero** [comment]
Hello,

You will need to run the **wider_eval.m** file, pointing the **pred_dir** variable to where you saved the predictions, and **legend_name** to the model name.

Hope this helps.
