### ISSUE TITLE
Is there a preferred size for the images?

### ISSUE THREAD

**Issue by LightingMc** [vitoralbiero/img2pose#9]
Good morning,
    Does img2pose automatically resize the facial images to a preferred size? Sorry, I am just being a bit lazy with reading the code.
Regards,
Zaigham

**Comment by vitoralbiero** [comment]
Good morning,
It depends on how the model was trained, in the case of the pre-trained version available, we trained using sizes from 600 to 800 pixels, so anything in between should work fine.
If you have images with a single face that are very large, you can reduce the image to sizes below 600 pixels, as there are almost no very large faces on the WIDER FACE dataset, and having the face smaller than 600 may help.

Hope this helps.
